name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run llama.cpp
        uses: psm14/llama-cpp-action@${{ github.sha }}
