name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run llama.cpp
        uses: ./
        with:
          prompt: Write me an essay about the man-made wonders of the world
